apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-example
  namespace: app-example
spec:
  secretName: app-example-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: app-example.example.com
  dnsNames:
    - app-example.example.com