apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rr-and-app
  namespace: app-example
spec:
  endpoints:
    - port: metrics
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: app-example