apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: metallb
    namespace: metallb-system
spec:
    interval: 1m0s
    url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: metallb
    namespace: metallb-system
spec:
    chart:
        spec:
            chart: metallb
            sourceRef:
                kind: HelmRepository
                name: metallb
            version: '*'
    interval: 1m0s