apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
data:
    alertmanager.yaml: ENC[AES256_GCM,data:uyTh4joH+MZcBAavnb03uUxCcnLuos5aRdALsm8cBate6UobY35Vd9IJLsru5wmDSiQTXTGfN6bju9MpuzYVhkXNhlEXjQQrOaVPaRKytHIU8lUXoPJq+NaB933OnOvccaHDvqsvxrAda19NJWim/LlJj2jTrCc/cKch4jNG05+lR0kOfvfW8a2FDmV0BcGuMa/C9lmNZRtz/h3CW0XBUUTUAilDxdXsCnJg07S+z/cy56dnE9CpbrHLzF8pgiDElQ2yTxtYeeb+kio1ASdlLOfkPLoHTco9/V/snDegLTWfpcEVyEHlLSOM+VtecPVzZn37peBEQ3+AVGiPkp1jMYr3XJDiJiGU9djW9041E1pVBAu2zQgeP9g8jZbrqjwOIG3SGv6T2V7vAR8Ad6B8ThptDhlw9XbY3uHF4tnB8DoYeI7lG+hTsu4VbNzy5r4whX5n0+YjRfRhJ/RWaA0ePGVSRKB4CdeQS0jA1tD/iO0EXTaydk0PUvkZqvrWmlpAE8mGH/eqHkNBdrnVo1kJo/kWwvyM2IuFLPxp3ZjZ1Al4RS0BGDATOG5Qj2FC6O1rqnqEUtWzmXnByA319KETEtnQD7wk/bYYcXQD5/7x3RzZnIythYbIQQJCiSFexoINX5QFcLkK7f4CtxZdHghu8sEu7bGCQlKji2e2PamKJOgbwZXUy9Fxq6GhvGHsac8XPjeCgT1I1UCZqHN9fLyMpIW9L2GrM1+Kxvs+OkcqKAxFBvAAnLTJ0Q4PITISzFxoHr+QAolEadXTbm+ilBGxVjLUnKaQac4AWKze8Rl+VIfASPh7H4coK/9Zy2Di7G4E/RJhPOUD0FI5PDF/80xiPHaenP5nZ8Ard9UaWAzzCPL4TWOXpJe5hrS0lHMGUAXCIVdCYuzVa4S8XcK0NAY1hlyWMApdR2m46UGQWhX/+KkiKXmuYn0UdBQU3pXo,iv:Vj2tf63IApfsFhyXx4WDlC18OBuEH9YW3W8vmSp+e/4=,tag:Le3fj4rF6V8OIvXq5EFOvA==,type:str]
sops:
    lastmodified: "2025-06-29T07:23:00Z"
    mac: ENC[AES256_GCM,data:W2NJjShWGFu+EqkW7T2xAqVeXCnOnPK/Ow7aCi0D17o7hNNjqxgQlZFHOcHZg0xeVFpc0GL5NHD0aFmSHCY4wRFO75KTRkNpbyrMfmpLC4j/m2Ico7IqhldpvAyoDwRgM3s9hmjBW/RgSmYkWCAigXT8qeUwKWNC2l+0zbMnSfk=,iv:rtI+6ou6BRi2BrH6/wyYw4XHaKtZ/RPm93vEn7IkMZI=,tag:0TDce4Nki3uIbQZDXb3d3w==,type:str]
    pgp:
        - created_at: "2025-06-29T07:23:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2/Jwk+/uhSBAQ//fnyzAp3UOwZ/4Iabpzgdhn+GWuRBFSE0tgRUbOmWugGK
            sfs82JLCa6fKZauQW//kTuBJduNF3KD1BWR64mfwbFIIvTbq+fxagXxuvQyBruGp
            3CJiFd7o3LHayloq3Of4V3PxH50FzRPpNKYlBayohkzzLm26zRHK3oUUR3c5HfVv
            Ap/HpQI0Z30aRz2TycLwRs1M8eSmRRbOBLpqQujR0JQXbj8sYcMc7lL2WJmbf0Wa
            OJQgituWIa2I2XErugNPPgEnLpipelHrs16aAOj0+/fJGUNpDrPbPCNSbnGehLkP
            1fIxebwTXX5eRiYZRmZjPByRYN2d8Msamt3r7yCsEufJlRrG9Zzwn4zS3/UXnIkV
            Z1ELTLLysZax09vFjjq32KYK0ap6CXnHvunRAZShJACDjSjYdVcfBFPNGaMewJmF
            JExyzaZsyWTcOmKsKEVR6vuMlIZvULg5viNjVBAVYp+6knOWS7qLsm1+zye5+7Io
            PdYBsI0s8Kit3EA4Ez7wZsRbCsRhoZl+G45k8IxQX5ItAajlIpKGyc5YD2RbKYRo
            NwL0w7JSL1nFjypmqX6E4x36H8mL8woPe+oxfd3xI/0fdE69p3jYHNQGYyt10Z4s
            Po/GVVSc4pZe0LV3eUuAMAmL1HJQN69zkT2XAbqxR04ouomulicWkfGBrtyiyMfS
            XgFx72iSEzYZt3pO7sUJsPR0Dh3jpo7EpOzRMJ7Mxyb78pMscXJ2b3D3c5ijr0S6
            Me6iloiztLB31htiDTNZ7PG1udu8iPn9aqzK+hDZwKAMwHLVgHUwV2oKex4aLx0=
            =h1fL
            -----END PGP MESSAGE-----
          fp: B1B740FC8FCA25D9BE0C118CED0FB16FAF7A8471
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
