apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-rules
  namespace: monitoring
spec:
  groups:
    - name: k8s-rules
      rules:
        - alert: ZeroDeploymentPods
          expr: kube_deployment_status_replicas_available == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            description: "Количество подов равно 0!"
            summary: "Количество подов деплоймента {{ $labels.deployment }} в namespace {{ $labels.namespace }} равно нулю!"