apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - 01-metallb-install.yaml
    - 02-metallb-config.yaml
    - 03-ingress-nginx.yaml
    - 04-cert-manager.yaml
    - 05-letsencrypt.yaml
    - 06-app.yaml
    - ./flux-system