apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - 01-metallb-install.yaml
    - 02-metallb-config.yaml
    - 03-ingress-nginx.yaml
    - 04-cert-manager.yaml
    - 05-letsencrypt.yaml
    - 06-local-path-provisioner.yaml
    - 07-app-example-namespace.yaml
    - 08-postgres-operator.yaml
    - 09-postgres.yaml
    - 10-app.yaml
    - 11-loki.yaml
    - ./flux-system