apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: ingress-nginx
    namespace: ingress-nginx
spec:
    interval: 1m0s
    url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ingress-nginx
    namespace: ingress-nginx
spec:
    chart:
        spec:
            chart: ingress-nginx
            sourceRef:
                kind: HelmRepository
                name: ingress-nginx
            version: '*'
    interval: 1m0s