apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
    namespace: grafana
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:aUqLfuY=,iv:VaOTddpFC/5L0OEUO8QBQc7wwvRJGegGqfMzoTaEdu4=,tag:bMo96lTDGaGrbfRcQEzwpw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Mk/GyLkw,iv:SN9rCmSDbbkG123IZ6ss0ubLvN86YxcueK1MEUGaty8=,tag:WG/EP9jop+7EIPROBKSmzw==,type:str]
sops:
    lastmodified: "2025-04-27T08:17:52Z"
    mac: ENC[AES256_GCM,data:KBd6tmONhHvHTT3JU4iIinXZylNU06nzCk4fes1ZmhhHV8s6civ//s63uyYMOS6D+P6hx3cnItYp3oAe1TP/JnQxadLM41W8jjWW9QRSSkoCO6mxNifpvbZDXP9oXf+C03xst7xhfD/mgV0Y/aWv5i4YtqBonLQPXFIpZNQH61I=,iv:Kt75baPHOx82Z46uZivRD8YUYQg/B76JikIUCopFtqY=,tag:idbJgDiU5IqzBfiolSmliw==,type:str]
    pgp:
        - created_at: "2025-04-27T08:17:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2/Jwk+/uhSBAQ//alIGSEX2WSXBf1jyqvdKZ81KpBR8a/7jYmsNtI9IR5KH
            aA+Mb1InmkwPdqgICfakLzMV0UoJX0/6V+tJbO3P9A125NQTbNodv7Csns6Xv6/R
            F4ZDFp4ZPEy0IoFRZIPfoOMJAefxGBsyF0ziUPK9Yhr5l2vLna5ejpx9Hz9kBADo
            ngKcGONrE7lpsKe2f0gduBbGFhAAPoVZ1A30/g7tlWY/Hdc9dtMpN3nC+dPZ4ncJ
            TelEjhDfywMdf466W2n8ZB5YajYMeCVOa+4zmENu6TFQcGwN6M+D4VGRYl6Dqhxv
            0/J1Xz/s2u13s52NXhvWzuj7k7XRRwDPwFh1u9foIKrBGZcbXN5M+d68TyN5rPMV
            Jd45Psga4ps5MRCQYtU3e3jrocDYMCvzQGkbKSVOwF4C7c3F6lCsKpNVYFgtg4y3
            k8niPoDi2ckfJ44I2CKIQGzYuD2c6MULqS6bYg5grorxVShEqMR/+LKLq/XXlGKH
            9ZR8iYXCgX3VoUjwKa3wZNFP5EMzuU0302GgQaE03RLixvjZvfrNXs87HBG6MdHo
            DUhQlsCx/W4QSKWl2ESgY5dqnvA8oTG3bfEu2Z6D/G3XVztaUnLaNB+EIUtYoRu5
            Ii4gjB43eSIZw+W7aIHxkq4KUuVo69bPX2IhgTf+juxKNHSLyoGcvzZJLpCp43PS
            XgEWoRvKStc+7XyZt3sW+eErYThRpAhhwQUDDZAZNR15Xy23LgpafbXKpzpk1cfh
            0q1wsWZA/qeotIJKVPBza8spRwGpo8GAk05BzwxxV2hNkN5olCV/MolFZH4XiZs=
            =X8ok
            -----END PGP MESSAGE-----
          fp: B1B740FC8FCA25D9BE0C118CED0FB16FAF7A8471
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
