apiVersion: v1
kind: Secret
metadata:
    name: loki-envs
    namespace: loki
stringData:
    S3_LOKI_ENDPOINT: ENC[AES256_GCM,data:r5Epz3fTTadVCEwNCGisjg==,iv:exqPPk7p6QMCEJONwW3I98YLYc1lpiVXHFA+fZuzyp8=,tag:hjtoNh2Eh3U4C8Epi/lZLQ==,type:str]
    S3_LOKI_DSN: ENC[AES256_GCM,data:ZVUyWPuPrwVhMcoJ9LFYjC4CwLzC8xDZbVyHlpxzFfQkzKtz/AvRVp9SraB5F0I3tlHuYZvNiNdWa11Ltrw63dT2qLz2mLnQb/eDh9kIrivZPmGQIZkI,iv:wdHztrwFUeb7ReYEe/S/o2aASp8XxWFgz4Eum0IxSnc=,tag:lqgDa7APqCWm/kRjCskRNQ==,type:str]
    S3_LOKI_REGION: ENC[AES256_GCM,data:XuMift0=,iv:h63Pm+nkYCMoWuK7rBDB7IFHveQh+usy9CNoI+m2Xw4=,tag:ZITdF9d0lrlieQinX9UKpQ==,type:str]
    S3_LOKI_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oGyX6eHPyGIylobDYyVy8hrwldBnfsaY/bygRtWY/sbuJp016IIuaw==,iv:BlKFRGRLswRcYuROTxc0+uqihxYWdssHt1V73QDSK04=,tag:xqXaXZDMbecshJLtGMVK6Q==,type:str]
    S3_LOKI_ACCESS_KEY_ID: ENC[AES256_GCM,data:TZyX1iHKmz6i+QfOb+HGeJoPPV4=,iv:pDh5aC5GJ50kF65GPEPmgEo4SKiSEPW2qAEq1Rx6MNI=,tag:h07IWBO9PUV91YpOy3Lb2w==,type:str]
    S3_LOKI_INSECURE: ENC[AES256_GCM,data:sVZNhYM=,iv:0Fwq96rCphTyDeqGGQZDdKW9VvbGplf2hoKuWOvUuNQ=,tag:29qjwqtcUAER/ZkAiLHCFw==,type:str]
sops:
    lastmodified: "2025-04-06T07:06:17Z"
    mac: ENC[AES256_GCM,data:L62BdY2jjvItKg+wb9yQBnxH4dwkpop/BSmftRxpvv3HseihbU4vqEgmPRWS+GqFu02gKM4ic7DWCdLo4aFHyvvIQH6sQtP5DEaLubsiYqRVLWN5MkJMWsdcVtSY2AQBocoeBirZGS5iDF7KNgSL7Gr+1zvvxJ3pYzSBNA5JEls=,iv:tO8Rg1Ur0ren3b1T5MBQ689kLJ7Ya/eA1YKHCwlAiNE=,tag:OAnILLIMxdTYfy+kC+KAPw==,type:str]
    pgp:
        - created_at: "2025-04-06T07:06:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2/Jwk+/uhSBAQ//TPVw2wr7ZPHnk9/jEJMsTP4kk/o0++ZT/GCeS8JNlJXG
            bkzn80ZIA+G8T6VSGgkzGXTumC8kbm3K3J4vUIEDFp9FehMpB0es769NdbE0Lis3
            oXrpUlbNW2MxPSW3q2h5OJdA9y7D0ZhkqzuiK4C84V8iNGT9KCrDvsZMGG4mBWRa
            SH7SDzttkb+QeHSH/G2MUXF+xIo2TR9FPx9B65a/SC82WbRq2JULD28lDTF4YSpT
            wA89bmZaTE7RdsOQpgJ1nakBU2/wYxTUW5Orm0i7a46fc+2DwTxSSypLXs8wZr0s
            WykjnuCsFqLPIYo7h+Gxg5Xz0EhW79ufgpm2DvcFdN6B8t0QkZzku5QH+RzoLpjj
            WnISxUmvH1a5N5B4pMtbfzcVH+ZyCZhEREMJNRxfgNfYzThpzpdE9ELLw4IY8Vp5
            D4XMePrt/R5LobGkvykZuN21/0CK1Rh3mfplZBQ5x4SMTITMWCwY9JTba47Z0/OM
            OiMdOyB/+BQNC9AorNAv6L/G5ggCcudsbL8Zo2K0PMedDO5drnGuRjyWT+bJtq2w
            zE3FDumckxp0k6qOUM12XeRYP3Un9mrefHTGET7IXXYPSe+0Z9Oh8jEvBSi4LYb4
            TXc4Ys4qg5lI9kuSgMJN5dt/WtDG/thC4fdVeSOUChHHTO80oRJpkkTFowtkEOXS
            XgHBAMtoWMWP3ThTnCtbZuqfqIbeFxBZWO1kige1Wpf6QEX2kKwDpDTanrBoH2Y8
            O5gQzIsLlmCCZ8mHQR696JIn4tJDP7Rf2Mmvk7qnVvVUgdyHShxe/CRO0KZim3U=
            =qLdz
            -----END PGP MESSAGE-----
          fp: B1B740FC8FCA25D9BE0C118CED0FB16FAF7A8471
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
