apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - gotk-components.yaml
    - gotk-sync.yaml
patches:
    - patch: |
          # Allow Helm DNS lookups
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --feature-gates=AllowDNSLookups=true
      target:
          kind: Deployment
          name: helm-controller